const testLibertyScore = {
  "Board": [
    "B . B . . B .",
    ". B . B . B .",
    "B . B B B . B",
    "B B . B . . B",
    "W W W . . B B",
    "W . W W W W W",
    ". . W B W . .",
  ],
  "LibertyCount": [
    "2 . 3 . . 5 .",
    ". 4 . 8 . 5 .",
    "3 . 8 8 8 . 4",
    "3 3 . 8 . . 4",
    "8 8 8 . . 4 4",
    "8 . 8 8 8 8 8",
    ". . 8 0 8 . .",
  ],
  "Enclosed": [
    ". b . b b . b",
    "b . b . b . b",
    ". b . . . ? .",
    ". . ? . ? ? .",
    ". . . ? ? . .",
    ". w . . . . .",
    "w w . . . w w",
  ],
  "Score": [
    "B b B b b B b",
    "b B b B b B b",
    "B b B B B ? B",
    "B B ? B ? ? B",
    "W W W ? ? B B",
    "W w W W W W W",
    "w w W B W w w",
  ],
  "B": 27,
  "W": 16,
  "?": 6,
  [GO_BLACK]: 27,
  [GO_WHITE]: 16,
  [GO_STONE]: 6,
};
